export const EVENTS_SOCKET = {
  SIGN_IN_ROOM: 'SIGN_IN_ROOM',
  CREATE_ROOM: 'CREATE_ROOM',
  GET_ROOMS: 'GET_ROOMS',
  CHAT_LEAVE_USER: 'CHAT_LEAVE_USER',
  CHAT_NEW_USER: 'CHAT_NEW_USER',
  CHAT_MSG: 'CHAT_MSG',
  EDIT_MSG: 'EDIT_MSG',
  DELETE_MSG: 'DELETE_MSG',
  GET_USERS: 'GET_USERS',
  TURN_ROOT: 'TURN_ROOT',
  CHANGE_AVATAR: 'CHANGE_AVATAR',
  VOTING_FINISH: 'VOTING_FINISH',
  VOTING_RESULT: 'VOTING_RESULT',
  VOTING_INIT: 'VOTING_INIT',
  VOTING_POINT: 'VOTING_POINT'
}
